### PR TITLE
Show votes information on user page

### PR DESCRIPTION
**Pull request by taitus**
## References
Requirement:
> i. We would like for users to see how many votes their proposals got in their account. It is very difficult for them to campaign not knowing how the voting is going on their own project.

## Objectives
We show the number of votes when the budget is in the balloting phase or later and the project has been selected.
In all other cases we show "-", i.e. for budget phases before the balloting phase, or when a project has not been selected.

## Visual Changes
Show votes information on usre page

### CODE REVIEW

**Review by Senen — CHANGES_REQUESTED** [review]
Hi @taitus, 

I think we should not show the investment number of votes to other users 🤔 .

Maybe we can show the votes columns only when visiting your own account page but not when visiting other users' pages.

**Review by Senen — APPROVED** [review]

**Comment by taitus** [comment]
@decembrya Could you have a look at the text we're adding in Romanian? 🙏 Thanks!

**Comment by decembrya** [comment]
> @decembrya Could you have a look at the text we're adding in Romanian? 🙏 Thanks!

Looks good 👍

**Comment by taitus** [comment]
The test failure isn't related to this pull request.

**Pull request merged**
